### ISSUE TITLE
Create unit tests for swerve architecture 

### ISSUE THREAD

**Issue by kooryan** [TheGreenMachine/Zodiac#105]

**Comment by richiksc** [comment]
Dependency: add Mockito library and proper JUnit configuration to `master`, then merge into working branch.

Issue: #106

**Comment by richiksc** [comment]
@kooryan what kind of unit tests do we need to write for swerve?

**Comment by richiksc** [comment]
@kooryan This isn't done?

**Comment by kooryan** [comment]
duplicate of #101
