### ISSUE TITLE
Update CheezeCurd.config.yml to match K-9 repo

### ISSUE THREAD

**Issue by richiksc** [TheGreenMachine/Zodiac#116]
Currently, the CheezeCurd yml is in a state where Zodiac code is broken on it - pull the yml from the K-9 repo and make neccessary modifications to fix.

Complete before 24HoS presentation on Saturday, 12/19.

Note: add Pigeon IMU on CAN ID `13`.

**Comment by ianmcvann** [comment]
Go to all team.
