### ISSUE TITLE
Create Hopper 

### ISSUE THREAD

**Issue by kooryan** [TheGreenMachine/Zodiac#15]
hopper: 
- [x] Flapper: 1 solenoid 
- [x] ball elevator: 1 775 motor
- [x] spindexer: 1 775 motor

**Comment by richiksc** [comment]
Postponing to week 7 as solenoids on robot for feeder flap have still not been installed.

**Comment by richiksc** [comment]
Postponing to week 8 as solenoids on robot for feeder flap have still not been installed.
