### ISSUE TITLE
Create Climber

### ISSUE THREAD

**Issue by kooryan** [TheGreenMachine/Zodiac#18]
- [x] elevator: 1 775 motor
- [x] deployer: solenoid

**Comment by richiksc** [comment]
@kooryan Postpone this milestone, since climber is yet to be mounted on the robot?

**Comment by richiksc** [comment]
Postponing to week 8 as climber has yet to be mounted on test robot.

**Comment by kooryan** [comment]
Not working in correspondence to gamepad
