### ISSUE TITLE
Develop ZodiacVision pipeline/Code

### ISSUE THREAD

**Issue by ianmcvann** [TheGreenMachine/Zodiac#29]

**Comment by mgher** [comment]
Accidentally closed issue and tried to get it back into the right column. Sorry

**Comment by kooryan** [comment]
is this complete?

**Comment by richiksc** [comment]
@ianmcvann What's the status of this issue? The milestone is due this Sunday.

**Comment by ianmcvann** [comment]
No longer needed. Can be closed.
