### ISSUE TITLE
Create automodes for InfiniteRecharge

### ISSUE THREAD

**Issue by Aryan9101** [TheGreenMachine/Zodiac#30]
- [x] Autonomous period mode @richiksc 
- [x] Feeder to Trench Mode
- [x] Trench to Feeder Mode

~~Testing Blocked On: #39, #40~~

Testing:

- [x] AutoTrenchMode
- [x] Feeder To Trench
- [x] Trench To Feeder

**Comment by kooryan** [comment]
These should be developed on a new branch
